name: COMMENT_DEVELOP_FIX
on:
  pull_request:
    types: [opened, reopened]
permissions:
  pull-requests: write
jobs:
  comment-on-fix-to-develop:
    if: ${{ github.base_ref == 'develop' }}
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.number }}
          body: |
            A new PR was created!
          reactions: '+1'
