name: COMMENT_DEVELOP_FIX
on:
  pull_request:
    branches:
      - develop
permissions: write-all
jobs:
  comment-on-fix-to-develop:
    runs-on: ubuntu-latest
    steps:
      - name: Print commits
        run: echo "The commit messages are ${{ github.event.number }} ${{ github.event.commits }}"
      - name: Print head commit
        run: echo "The head commit message is ${{ github.event.head_commit.message }}"
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.number }}
          body: |
            This Pull Request targets `develop` branch, but contains `fix` commits.

            Consider targeting `master` instead.
