name: COMMENT_DEVELOP_FIX
on:
  pull_request_target:
    types: [open, reopen, edit]
    branches:
      - develop
permissions:
  pull-requests: write
jobs:
  comment-on-fix-to-develop:
    runs-on: ubuntu-latest
    steps:
      - name: Check for fix commits
        uses: gsactions/commit-message-checker@v1
        with:
          pattern: '^fix'
          error: 'Fixing commit discovered'
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.number }}
          body: |
            This Pull Request targets `develop` branch, but contains `fix` commits.

            Consider targeting `master` instead.
