name: COMMENT_DEVELOP_FIX
on:
  pull_request_target:
      branches:
        - develop
permissions:
  pull-requests: write
jobs:
  comment-on-fix-to-develop:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.number }}
          body: |
            This Pull Request targets `develop` branch, but contains `fix` commits.

            Consider targeting `master` instead.
