name: COMMENT_DEVELOP_FIX
on:
  pull_request:
    branches:
      - develop
permissions: write-all
jobs:
  comment-on-fix-to-develop:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ github.event.pull_request.commits_url }}
        run: echo "$GITHUB_CONTEXT"
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.number }}
          body: |
            This Pull Request targets `develop` branch, but contains `fix` commits.

            Consider targeting `master` instead.
