name: COMMENT_DEVELOP_FIX
on:
  pull_request:
    branches:
      - develop
permissions: write-all
jobs:
  comment-on-fix-to-develop:
    runs-on: ubuntu-latest
    steps:
      - name: Check for fix commits
        env:
          COMMITS_URL: ${{ github.event.pull_request.commits_url }}
        run: |
          echo "Checking commits via $COMMITS_URL"

          if [[ $(curl $COMMITS_URL) =~ ."\"message\": \"fix".* ]]
          then
            echo "Fix commit detected - continue to post comment"
          else
            echo "No fix commit detected - succesful exit"
            exit 0
          fi
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.number }}
          body: |
            This Pull Request targets `develop` branch, but contains `fix` commits.

            Consider targeting `master` instead.
